; PlatformIO Project Configuration File
;
;   Build options: build flags, source filter
;   Upload options: custom upload port, speed and extra flags
;   Library options: dependencies, extra library storages
;   Advanced options: extra scripting
;
; Please visit documentation for the other options and examples
; https://docs.platformio.org/page/projectconf.html

[env:esp32-s3-devkitm-1]
platform = espressif32
board = esp32-s3-devkitm-1
framework = arduino
lib_deps = 
	adafruit/Adafruit GFX Library@^1.12.6
	adafruit/Adafruit BusIO@^1.17.4
	adafruit/Adafruit ST7735 and ST7789 Library@^1.11.0
	adafruit/Adafruit SPIFlash@^5.1.1
	adafruit/SdFat - Adafruit Fork@^2.3.103
	adafruit/Adafruit ImageReader Library@^2.10.0
	adafruit/Adafruit HX8357 Library@^1.1.20

; Force PlatformIO to use COM8 for uploading and monitoring
upload_port = COM8
monitor_port = COM8
monitor_speed = 115200

; CRITICAL: These flags match the "USB CDC On Boot = Enabled" setting in Arduino
build_flags =
    -D ARDUINO_USB_CDC_ON_BOOT=1
    -D ARDUINO_USB_MODE=1
    
; Configure your specific N8R8 flash and PSRAM settings
board_upload.flash_size = 8MB
board_build.arduino.memory_type = qio_opi